#!/usr/bin/env bash

NAME="bdpurge"
CODENAME="bdpurge"
COPYRIGHT="Copyright (C) 2016 Nathan Shearer"
LICENSE="GNU General Public License 2.0"
VERSION="2.0.0.0"

# \brief Ensures dependencies are present
# \param $@ The dependencies to check for
function bdpurge_check_dependencies
{
	for TOOL in "$@"; do
		if ! type "$TOOL" >/dev/null 2>/dev/null; then
			echo "$CODENAME: \"$TOOL\" is required for this application to work correctly." >&2
			exit
		fi
	done
}

# \brief Erase data at both ends of a block device
# \param $1 The device
# \param $2 The amount of data to erase at each end
function bdpurge_erase_quick
{
	local DEVICE="$1"
	local PURGE_SIZE="$2"
	
	echo -n "Erasing the first and last $PURGE_SIZE bytes on \"$DEVICE\"..."
	
	local DEVICE_SIZE=$(blockdev --getsize64 "$DEVICE")
	
	if [ $(($PURGE_SIZE*2)) -ge "$DEVICE_SIZE" ]; then
		if $PRETEND; then
			echo
			echo dd status=none if=/dev/zero bs=512 count=$(($DEVICE_SIZE/512)) of="$DEVICE" >/dev/null 2>/dev/null
		else
			dd status=none if=/dev/zero bs=512 count=$(($DEVICE_SIZE/512)) of="$DEVICE" >/dev/null 2>/dev/null
		fi
	else
		if $PRETEND; then
			echo
			echo dd status=none if=/dev/zero bs=512 count=$(($PURGE_SIZE/512)) of="$DEVICE"
			echo dd status=none if=/dev/zero bs=512 count=$(($PURGE_SIZE/512)) of="$DEVICE" seek=$(($(($DEVICE_SIZE/512))-$(($PURGE_SIZE/512))))
		else
			dd status=none if=/dev/zero bs=512 count=$(($PURGE_SIZE/512)) of="$DEVICE"
			dd status=none if=/dev/zero bs=512 count=$(($PURGE_SIZE/512)) of="$DEVICE" seek=$(($(($DEVICE_SIZE/512))-$(($PURGE_SIZE/512))))
		fi

	fi
	
	if ! $PRETEND; then
		echo " done."
	fi
}

# \brief Perform a quick erase of each partition and the entire block device
# \param $1 The device
# \param $2 The amount of data to erase at each end
function bdpurge_erase_quickr
{
	local DEVICE="$1"
	local PURGE_SIZE="$2"
	
	for PARTITION in "$DEVICE"[0-9]* "$DEVICE"p[0-9]*; do
		if [ "$PARTITION" = "${DEVICE}[0-9]*" ]; then continue; fi
		if [ "$PARTITION" = "${DEVICE}p[0-9]*" ]; then continue; fi
		bdpurge_erase_quick "$PARTITION" "$PURGE_SIZE"
	done
	bdpurge_erase_quick "$DEVICE" "$PURGE_SIZE"
}

# \brief Displays the help and exits the program
function bdpurge_help
{
	#     01234567890123456789012345678901234567890123456789012345678901234567890123456789
	echo "Description:"
	echo "  Erase a block device"
	echo
	echo "Usage:"
	echo "  $CODENAME [options] BLOCK_DEVICE"
	echo
	echo "Options:"
	echo "  -f, --force"
	echo "    Erase the block device even if it is mounted."
	echo "  -h, --help"
	echo "    Display this help message and exit."
	echo "  -m, --method quick"
	echo "    Set the method used to erase the block device. Default is quick:"
	echo "      quick      Erase both ends of the device"
	echo "      quickr     Erase both ends of each partition and the device"
	#echo "      full       Write a sequence of zeros to the entire device"
	#echo "      badblocks  Write 4 passes of 0xaa, 0x55, 0xff. and 0x00"
	#echo "      scrub      Write multiple passes with data from /dev/urandom"
	echo "  -n N"
	echo "    Sets the niceness to N (default 0)."
	echo "  -p, --pretend"
	echo "    Performs a dry run and prints out what purge commands would be performed."
	echo "    Data is not actually purged."
	echo "  -s, --size 16777216"
	echo "    The amount of data to erase at both ends of the block device."
	echo
	echo "Examples:"
	echo "  $CODENAME -r -p /dev/disk/by-id/ata-ST8000AS0002-1NA17Z_00000000"
	echo
	echo "Version:"
	echo "  $NAME $VERSION"
	echo "  $COPYRIGHT"
	echo "  Licensed under $LICENSE"
	exit
}

# \brief Analyze a block device and display relevant information
# \param $1 The device
function bdpurge_analyze
{
	local DEVICE="$1"
	
	if [ ! -b "$DEVICE" ]; then
		echo "error: \"$DEVICE\" is not a block device"
		return 1
	fi
	if ! $FORCE && mount | grep "$DEVICE" >/dev/null; then
		echo "error: \"$DEVICE\" is currently mounted"
		return 2
	fi
	
	local DEVICE_MODEL=$(hdparm -I "$DEVICE" 2>/dev/null | grep --text 'Model Number' | cut -d ':' -f 2 | sed -r -e 's/ *(.*?) */\1/')
	local DEVICE_SERIAL=$(hdparm -I "$DEVICE" 2>/dev/null | grep --text 'Serial Number' | cut -d ':' -f 2 | sed -r -e 's/ *(.*?) */\1/')
	local DEVICE_SIZE=$(blockdev --getsize64 "$DEVICE")
	
	echo "Device: $DEVICE"
	if [ "$DEVICE_MODEL" != "" ]; then
		echo "  Model Number: $DEVICE_MODEL"
	fi
	if [ "$DEVICE_SERIAL" != "" ]; then
		echo "  Serial Number: $DEVICE_SERIAL"
	fi
	echo "  Size: $DEVICE_SIZE Bytes"
}


# \brief Erase data on a block device
# \param $1 The device
function bdpurge_main
{
	local DEVICE="$1"
	
	bdpurge_analyze "$DEVICE"
	local ANALYSIS=$?
	if [ $ANALYSIS -ne 0 ]; then
		return $ANALYSIS
	fi
	
	echo "Press CTRL+C to cancel"
	for SECONDS in `seq 10 -1 1`; do
		printf "\r${SECONDS} ... "
		sleep 1
	done
	printf "\r0 ... \n"
	
	case "$METHOD" in
		"quick")
			bdpurge_erase_quick "$DEVICE" "$PURGE_SIZE"
			;;
		"quickr")
			bdpurge_erase_quickr "$DEVICE" "$PURGE_SIZE"
			;;
		#"full")
			#bdpurge_erase_full
			#;;
		#"badblocks")
			#bdpurge_erase_badblocks
			#;;
		#"scrub")
			#bdpurge_erase_scrub
			#;;
		*)
			echo "error: invalid method \"$METHOD\""
			return 1
			;;
	esac
	
	if $PRETEND; then
		echo partprobe "$DEVICE"
	else
		partprobe "$DEVICE"
	fi
}

#------------------------------------------------------------------------------
# default configuration
#
FORCE=false
METHOD=quick
NICE=0
PRETEND=false
PURGE_SIZE=16777216

#------------------------------------------------------------------------------
# config files
#
if [ -r /etc/$CODENAME.conf ]; then
	. /etc/$CODENAME.conf
fi
if [ -r ~/.$CODENAME.conf ]; then
	. ~/.$CODENAME.conf
fi

#------------------------------------------------------------------------------
# command line arguments
#

if [ $# -eq 0 ]; then
	bdpurge_help
	exit 1
fi

THIS="$0"
while [ $# -ne 0 ]; do
	case "$1" in
		"-f"|"--force")
			FORCE=true
			shift
			;;
		"-h"|"--help")
			bdpurge_help
			exit
			;;
		"-m")
			METHOD="$2"
			shift 2
			;;
		"-n")
			NICE="$2"
			shift 2
			;;
		"-p"|"--pretend")
			PRETEND=true
			shift
			;;
		"-s"|"--size")
			PURGE_SIZE="$2"
			if [ $(($(($PURGE_SIZE/512))*512)) -ne "$PURGE_SIZE" ]; then
				PURGE_SIZE=$(($(($PURGE_SIZE/512))*512))
				echo "warning: The purge size is not a multiple of 512, rounding down from $2 to $PURGE_SIZE" 
			fi
			shift 2
			;;
		*)
			break;;
	esac
done

if [ $# -eq 0 ]; then
	echo "error: Missing BLOCK_DEVICE argument."
	exit 1
fi
if [ $# -gt 1 ]; then
	bdpurge_help
	exit 1
fi
DEVICE="$1"

#------------------------------------------------------------------------------
# prepare environment

bdpurge_check_dependencies blockdev dd partprobe sleep
renice $NICE $$ >/dev/null

#------------------------------------------------------------------------------
# begin execution

bdpurge_main "$1"
